// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/auth-service/internal/app/domain"
)

// NewAuthRepositoryMock creates a new instance of AuthRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepositoryMock {
	mock := &AuthRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthRepositoryMock is an autogenerated mock type for the AuthRepository type
type AuthRepositoryMock struct {
	mock.Mock
}

type AuthRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthRepositoryMock) EXPECT() *AuthRepositoryMock_Expecter {
	return &AuthRepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type AuthRepositoryMock
func (_mock *AuthRepositoryMock) CreateUser(ctx context.Context, email string, passwordHash string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthRepositoryMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type AuthRepositoryMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
func (_e *AuthRepositoryMock_Expecter) CreateUser(ctx interface{}, email interface{}, passwordHash interface{}) *AuthRepositoryMock_CreateUser_Call {
	return &AuthRepositoryMock_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, passwordHash)}
}

func (_c *AuthRepositoryMock_CreateUser_Call) Run(run func(ctx context.Context, email string, passwordHash string)) *AuthRepositoryMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthRepositoryMock_CreateUser_Call) Return(user *domain.User, err error) *AuthRepositoryMock_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthRepositoryMock_CreateUser_Call) RunAndReturn(run func(ctx context.Context, email string, passwordHash string) (*domain.User, error)) *AuthRepositoryMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type AuthRepositoryMock
func (_mock *AuthRepositoryMock) FindUserByEmail(ctx context.Context, email string) (*domain.UserWithPassword, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.UserWithPassword
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.UserWithPassword, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.UserWithPassword); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserWithPassword)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthRepositoryMock_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type AuthRepositoryMock_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthRepositoryMock_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *AuthRepositoryMock_FindUserByEmail_Call {
	return &AuthRepositoryMock_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *AuthRepositoryMock_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *AuthRepositoryMock_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepositoryMock_FindUserByEmail_Call) Return(userWithPassword *domain.UserWithPassword, err error) *AuthRepositoryMock_FindUserByEmail_Call {
	_c.Call.Return(userWithPassword, err)
	return _c
}

func (_c *AuthRepositoryMock_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.UserWithPassword, error)) *AuthRepositoryMock_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type AuthRepositoryMock
func (_mock *AuthRepositoryMock) GetUserInfo(ctx context.Context, user_id uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, user_id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, user_id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthRepositoryMock_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type AuthRepositoryMock_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - user_id uuid.UUID
func (_e *AuthRepositoryMock_Expecter) GetUserInfo(ctx interface{}, user_id interface{}) *AuthRepositoryMock_GetUserInfo_Call {
	return &AuthRepositoryMock_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, user_id)}
}

func (_c *AuthRepositoryMock_GetUserInfo_Call) Run(run func(ctx context.Context, user_id uuid.UUID)) *AuthRepositoryMock_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepositoryMock_GetUserInfo_Call) Return(user *domain.User, err error) *AuthRepositoryMock_GetUserInfo_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthRepositoryMock_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, user_id uuid.UUID) (*domain.User, error)) *AuthRepositoryMock_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
