// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/auth-service/internal/app/domain"
)

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Login(ctx context.Context, email string, password string) (*domain.Tokens, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Tokens, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Tokens); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServiceMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthServiceMock_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *AuthServiceMock_Login_Call {
	return &AuthServiceMock_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *AuthServiceMock_Login_Call) Run(run func(ctx context.Context, email string, password string)) *AuthServiceMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Login_Call) Return(tokens *domain.Tokens, err error) *AuthServiceMock_Login_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *AuthServiceMock_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.Tokens, error)) *AuthServiceMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Logout(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthServiceMock_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthServiceMock_Expecter) Logout(ctx interface{}, token interface{}) *AuthServiceMock_Logout_Call {
	return &AuthServiceMock_Logout_Call{Call: _e.mock.On("Logout", ctx, token)}
}

func (_c *AuthServiceMock_Logout_Call) Run(run func(ctx context.Context, token string)) *AuthServiceMock_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Logout_Call) Return(err error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_Logout_Call) RunAndReturn(run func(ctx context.Context, token string) error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) RefreshTokens(ctx context.Context, token string) (*domain.Tokens, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *domain.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Tokens, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Tokens); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type AuthServiceMock_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthServiceMock_Expecter) RefreshTokens(ctx interface{}, token interface{}) *AuthServiceMock_RefreshTokens_Call {
	return &AuthServiceMock_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, token)}
}

func (_c *AuthServiceMock_RefreshTokens_Call) Run(run func(ctx context.Context, token string)) *AuthServiceMock_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_RefreshTokens_Call) Return(tokens *domain.Tokens, err error) *AuthServiceMock_RefreshTokens_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *AuthServiceMock_RefreshTokens_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.Tokens, error)) *AuthServiceMock_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Register(ctx context.Context, email string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthServiceMock_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthServiceMock_Expecter) Register(ctx interface{}, email interface{}, password interface{}) *AuthServiceMock_Register_Call {
	return &AuthServiceMock_Register_Call{Call: _e.mock.On("Register", ctx, email, password)}
}

func (_c *AuthServiceMock_Register_Call) Run(run func(ctx context.Context, email string, password string)) *AuthServiceMock_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Register_Call) Return(user *domain.User, err error) *AuthServiceMock_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthServiceMock_Register_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.User, error)) *AuthServiceMock_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UserInfo provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) UserInfo(ctx context.Context, user_id uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, user_id)

	if len(ret) == 0 {
		panic("no return value specified for UserInfo")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, user_id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, user_id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_UserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserInfo'
type AuthServiceMock_UserInfo_Call struct {
	*mock.Call
}

// UserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - user_id uuid.UUID
func (_e *AuthServiceMock_Expecter) UserInfo(ctx interface{}, user_id interface{}) *AuthServiceMock_UserInfo_Call {
	return &AuthServiceMock_UserInfo_Call{Call: _e.mock.On("UserInfo", ctx, user_id)}
}

func (_c *AuthServiceMock_UserInfo_Call) Run(run func(ctx context.Context, user_id uuid.UUID)) *AuthServiceMock_UserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_UserInfo_Call) Return(user *domain.User, err error) *AuthServiceMock_UserInfo_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthServiceMock_UserInfo_Call) RunAndReturn(run func(ctx context.Context, user_id uuid.UUID) (*domain.User, error)) *AuthServiceMock_UserInfo_Call {
	_c.Call.Return(run)
	return _c
}
