// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/auth-service/internal/domain"
)

// NewOAuthServiceMock creates a new instance of OAuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthServiceMock {
	mock := &OAuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthServiceMock is an autogenerated mock type for the OAuthService type
type OAuthServiceMock struct {
	mock.Mock
}

type OAuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthServiceMock) EXPECT() *OAuthServiceMock_Expecter {
	return &OAuthServiceMock_Expecter{mock: &_m.Mock}
}

// GetAuthCodeURL provides a mock function for the type OAuthServiceMock
func (_mock *OAuthServiceMock) GetAuthCodeURL(ctx context.Context, state string) string {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthCodeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// OAuthServiceMock_GetAuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthCodeURL'
type OAuthServiceMock_GetAuthCodeURL_Call struct {
	*mock.Call
}

// GetAuthCodeURL is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *OAuthServiceMock_Expecter) GetAuthCodeURL(ctx interface{}, state interface{}) *OAuthServiceMock_GetAuthCodeURL_Call {
	return &OAuthServiceMock_GetAuthCodeURL_Call{Call: _e.mock.On("GetAuthCodeURL", ctx, state)}
}

func (_c *OAuthServiceMock_GetAuthCodeURL_Call) Run(run func(ctx context.Context, state string)) *OAuthServiceMock_GetAuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthServiceMock_GetAuthCodeURL_Call) Return(s string) *OAuthServiceMock_GetAuthCodeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *OAuthServiceMock_GetAuthCodeURL_Call) RunAndReturn(run func(ctx context.Context, state string) string) *OAuthServiceMock_GetAuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetGenerateState provides a mock function for the type OAuthServiceMock
func (_mock *OAuthServiceMock) GetGenerateState(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGenerateState")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthServiceMock_GetGenerateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGenerateState'
type OAuthServiceMock_GetGenerateState_Call struct {
	*mock.Call
}

// GetGenerateState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OAuthServiceMock_Expecter) GetGenerateState(ctx interface{}) *OAuthServiceMock_GetGenerateState_Call {
	return &OAuthServiceMock_GetGenerateState_Call{Call: _e.mock.On("GetGenerateState", ctx)}
}

func (_c *OAuthServiceMock_GetGenerateState_Call) Run(run func(ctx context.Context)) *OAuthServiceMock_GetGenerateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OAuthServiceMock_GetGenerateState_Call) Return(s string, err error) *OAuthServiceMock_GetGenerateState_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *OAuthServiceMock_GetGenerateState_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *OAuthServiceMock_GetGenerateState_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserFromCode provides a mock function for the type OAuthServiceMock
func (_mock *OAuthServiceMock) GetUserFromCode(ctx context.Context, code string, state string) (*domain.ProviderUser, error) {
	ret := _mock.Called(ctx, code, state)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFromCode")
	}

	var r0 *domain.ProviderUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.ProviderUser, error)); ok {
		return returnFunc(ctx, code, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.ProviderUser); ok {
		r0 = returnFunc(ctx, code, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProviderUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, code, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthServiceMock_GetUserFromCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFromCode'
type OAuthServiceMock_GetUserFromCode_Call struct {
	*mock.Call
}

// GetUserFromCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - state string
func (_e *OAuthServiceMock_Expecter) GetUserFromCode(ctx interface{}, code interface{}, state interface{}) *OAuthServiceMock_GetUserFromCode_Call {
	return &OAuthServiceMock_GetUserFromCode_Call{Call: _e.mock.On("GetUserFromCode", ctx, code, state)}
}

func (_c *OAuthServiceMock_GetUserFromCode_Call) Run(run func(ctx context.Context, code string, state string)) *OAuthServiceMock_GetUserFromCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OAuthServiceMock_GetUserFromCode_Call) Return(providerUser *domain.ProviderUser, err error) *OAuthServiceMock_GetUserFromCode_Call {
	_c.Call.Return(providerUser, err)
	return _c
}

func (_c *OAuthServiceMock_GetUserFromCode_Call) RunAndReturn(run func(ctx context.Context, code string, state string) (*domain.ProviderUser, error)) *OAuthServiceMock_GetUserFromCode_Call {
	_c.Call.Return(run)
	return _c
}
