// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenServiceMock creates a new instance of TokenServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenServiceMock {
	mock := &TokenServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenServiceMock is an autogenerated mock type for the TokenService type
type TokenServiceMock struct {
	mock.Mock
}

type TokenServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenServiceMock) EXPECT() *TokenServiceMock_Expecter {
	return &TokenServiceMock_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type TokenServiceMock
func (_mock *TokenServiceMock) GenerateAccessToken(userID uuid.UUID) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceMock_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type TokenServiceMock_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *TokenServiceMock_Expecter) GenerateAccessToken(userID interface{}) *TokenServiceMock_GenerateAccessToken_Call {
	return &TokenServiceMock_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID)}
}

func (_c *TokenServiceMock_GenerateAccessToken_Call) Run(run func(userID uuid.UUID)) *TokenServiceMock_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenServiceMock_GenerateAccessToken_Call) Return(s string, err error) *TokenServiceMock_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenServiceMock_GenerateAccessToken_Call) RunAndReturn(run func(userID uuid.UUID) (string, error)) *TokenServiceMock_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type TokenServiceMock
func (_mock *TokenServiceMock) GenerateRefreshToken() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceMock_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type TokenServiceMock_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
func (_e *TokenServiceMock_Expecter) GenerateRefreshToken() *TokenServiceMock_GenerateRefreshToken_Call {
	return &TokenServiceMock_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken")}
}

func (_c *TokenServiceMock_GenerateRefreshToken_Call) Run(run func()) *TokenServiceMock_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenServiceMock_GenerateRefreshToken_Call) Return(s string, err error) *TokenServiceMock_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenServiceMock_GenerateRefreshToken_Call) RunAndReturn(run func() (string, error)) *TokenServiceMock_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashRefreshToken provides a mock function for the type TokenServiceMock
func (_mock *TokenServiceMock) HashRefreshToken(refreshToken string) (string, time.Time) {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for HashRefreshToken")
	}

	var r0 string
	var r1 time.Time
	if returnFunc, ok := ret.Get(0).(func(string) (string, time.Time)); ok {
		return returnFunc(refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) time.Time); ok {
		r1 = returnFunc(refreshToken)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	return r0, r1
}

// TokenServiceMock_HashRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashRefreshToken'
type TokenServiceMock_HashRefreshToken_Call struct {
	*mock.Call
}

// HashRefreshToken is a helper method to define mock.On call
//   - refreshToken string
func (_e *TokenServiceMock_Expecter) HashRefreshToken(refreshToken interface{}) *TokenServiceMock_HashRefreshToken_Call {
	return &TokenServiceMock_HashRefreshToken_Call{Call: _e.mock.On("HashRefreshToken", refreshToken)}
}

func (_c *TokenServiceMock_HashRefreshToken_Call) Run(run func(refreshToken string)) *TokenServiceMock_HashRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenServiceMock_HashRefreshToken_Call) Return(s string, time1 time.Time) *TokenServiceMock_HashRefreshToken_Call {
	_c.Call.Return(s, time1)
	return _c
}

func (_c *TokenServiceMock_HashRefreshToken_Call) RunAndReturn(run func(refreshToken string) (string, time.Time)) *TokenServiceMock_HashRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type TokenServiceMock
func (_mock *TokenServiceMock) ValidateAccessToken(accessToken string) (*jwt.RegisteredClaims, error) {
	ret := _mock.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *jwt.RegisteredClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.RegisteredClaims, error)); ok {
		return returnFunc(accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.RegisteredClaims); ok {
		r0 = returnFunc(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.RegisteredClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceMock_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type TokenServiceMock_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - accessToken string
func (_e *TokenServiceMock_Expecter) ValidateAccessToken(accessToken interface{}) *TokenServiceMock_ValidateAccessToken_Call {
	return &TokenServiceMock_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", accessToken)}
}

func (_c *TokenServiceMock_ValidateAccessToken_Call) Run(run func(accessToken string)) *TokenServiceMock_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenServiceMock_ValidateAccessToken_Call) Return(registeredClaims *jwt.RegisteredClaims, err error) *TokenServiceMock_ValidateAccessToken_Call {
	_c.Call.Return(registeredClaims, err)
	return _c
}

func (_c *TokenServiceMock_ValidateAccessToken_Call) RunAndReturn(run func(accessToken string) (*jwt.RegisteredClaims, error)) *TokenServiceMock_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
