// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/auth-service/internal/app/domain"
)

// NewTokenRepositoryMock creates a new instance of TokenRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenRepositoryMock {
	mock := &TokenRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenRepositoryMock is an autogenerated mock type for the TokenRepository type
type TokenRepositoryMock struct {
	mock.Mock
}

type TokenRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenRepositoryMock) EXPECT() *TokenRepositoryMock_Expecter {
	return &TokenRepositoryMock_Expecter{mock: &_m.Mock}
}

// DeleteRefreshToken provides a mock function for the type TokenRepositoryMock
func (_mock *TokenRepositoryMock) DeleteRefreshToken(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenRepositoryMock_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type TokenRepositoryMock_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *TokenRepositoryMock_Expecter) DeleteRefreshToken(ctx interface{}, tokenHash interface{}) *TokenRepositoryMock_DeleteRefreshToken_Call {
	return &TokenRepositoryMock_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, tokenHash)}
}

func (_c *TokenRepositoryMock_DeleteRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *TokenRepositoryMock_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenRepositoryMock_DeleteRefreshToken_Call) Return(refreshToken *domain.RefreshToken, err error) *TokenRepositoryMock_DeleteRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *TokenRepositoryMock_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*domain.RefreshToken, error)) *TokenRepositoryMock_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshToken provides a mock function for the type TokenRepositoryMock
func (_mock *TokenRepositoryMock) FindRefreshToken(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshToken")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenRepositoryMock_FindRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshToken'
type TokenRepositoryMock_FindRefreshToken_Call struct {
	*mock.Call
}

// FindRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *TokenRepositoryMock_Expecter) FindRefreshToken(ctx interface{}, tokenHash interface{}) *TokenRepositoryMock_FindRefreshToken_Call {
	return &TokenRepositoryMock_FindRefreshToken_Call{Call: _e.mock.On("FindRefreshToken", ctx, tokenHash)}
}

func (_c *TokenRepositoryMock_FindRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *TokenRepositoryMock_FindRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenRepositoryMock_FindRefreshToken_Call) Return(refreshToken *domain.RefreshToken, err error) *TokenRepositoryMock_FindRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *TokenRepositoryMock_FindRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*domain.RefreshToken, error)) *TokenRepositoryMock_FindRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveHashedRefreshToken provides a mock function for the type TokenRepositoryMock
func (_mock *TokenRepositoryMock) SaveHashedRefreshToken(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveHashedRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenRepositoryMock_SaveHashedRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHashedRefreshToken'
type TokenRepositoryMock_SaveHashedRefreshToken_Call struct {
	*mock.Call
}

// SaveHashedRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenHash string
//   - expiresAt time.Time
func (_e *TokenRepositoryMock_Expecter) SaveHashedRefreshToken(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *TokenRepositoryMock_SaveHashedRefreshToken_Call {
	return &TokenRepositoryMock_SaveHashedRefreshToken_Call{Call: _e.mock.On("SaveHashedRefreshToken", ctx, userID, tokenHash, expiresAt)}
}

func (_c *TokenRepositoryMock_SaveHashedRefreshToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time)) *TokenRepositoryMock_SaveHashedRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenRepositoryMock_SaveHashedRefreshToken_Call) Return(err error) *TokenRepositoryMock_SaveHashedRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenRepositoryMock_SaveHashedRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) error) *TokenRepositoryMock_SaveHashedRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
