// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package pggen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (email, provider_id, oauth_provider)
VALUES ($1, $2, $3)
RETURNING user_id, email, created_at, is_active, provider_id, oauth_provider
`

type CreateOAuthUserParams struct {
	Email         string
	ProviderID    sql.NullString
	OauthProvider sql.NullString
}

type CreateOAuthUserRow struct {
	UserID        uuid.UUID
	Email         string
	CreatedAt     time.Time
	IsActive      bool
	ProviderID    sql.NullString
	OauthProvider sql.NullString
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (CreateOAuthUserRow, error) {
	row := q.db.QueryRowContext(ctx, createOAuthUser, arg.Email, arg.ProviderID, arg.OauthProvider)
	var i CreateOAuthUserRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.IsActive,
		&i.ProviderID,
		&i.OauthProvider,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES($1, $2)
RETURNING user_id, email, created_at, is_active, provider_id, oauth_provider
`

type CreateUserParams struct {
	Email        string
	PasswordHash sql.NullString
}

type CreateUserRow struct {
	UserID        uuid.UUID
	Email         string
	CreatedAt     time.Time
	IsActive      bool
	ProviderID    sql.NullString
	OauthProvider sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.IsActive,
		&i.ProviderID,
		&i.OauthProvider,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT user_id, email, password_hash, created_at, is_active, provider_id, oauth_provider
FROM users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsActive,
		&i.ProviderID,
		&i.OauthProvider,
	)
	return i, err
}

const findUserByProviderID = `-- name: FindUserByProviderID :one
SELECT user_id, email, password_hash, created_at, is_active, provider_id, oauth_provider
FROM users
WHERE provider_id = $1 AND oauth_provider = $2
`

type FindUserByProviderIDParams struct {
	ProviderID    sql.NullString
	OauthProvider sql.NullString
}

func (q *Queries) FindUserByProviderID(ctx context.Context, arg FindUserByProviderIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByProviderID, arg.ProviderID, arg.OauthProvider)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsActive,
		&i.ProviderID,
		&i.OauthProvider,
	)
	return i, err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT user_id, email, created_at, is_active, provider_id, oauth_provider
FROM users
WHERE user_id = $1
`

type GetUserInfoRow struct {
	UserID        uuid.UUID
	Email         string
	CreatedAt     time.Time
	IsActive      bool
	ProviderID    sql.NullString
	OauthProvider sql.NullString
}

func (q *Queries) GetUserInfo(ctx context.Context, userID uuid.UUID) (GetUserInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfo, userID)
	var i GetUserInfoRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.IsActive,
		&i.ProviderID,
		&i.OauthProvider,
	)
	return i, err
}
