// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pggen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Token struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	CreatedAt        time.Time
	ExpiresAt        time.Time
}

type User struct {
	UserID        uuid.UUID
	Email         string
	PasswordHash  sql.NullString
	CreatedAt     time.Time
	IsActive      bool
	ProviderID    sql.NullString
	OauthProvider sql.NullString
}
